import { Theme as T } from "../Theme.slint";

component ComboBox-Button inherits Rectangle {

    in property <int> id: 0;
    in property <bool> alive: false;
    in property <string> title: "Button";
    in property <length> font-size: T.font4;
    in property <TextHorizontalAlignment> alignment: left;

    callback clicked(int);

    border-radius: T.bor-radius;

    touch := TouchArea {
        clicked => {
            root.clicked(root.id);
        }
    }

    HorizontalLayout {

        padding-top: T.gap / 2;
        padding-bottom: self.padding-top;
        padding-left: T.gap;
        padding-right: self.padding-left;

        spacing: T.gap / 2;

        name := Text {
            text: root.title;
            font-size: root.font-size;
            horizontal-alignment: root.alignment;
            vertical-alignment: center;

            states [
                alive when alive: {
                    color: T.bg1;
                    font-weight: 800;
                }
                none when !touch.has-hover && !alive: {
                    color: T.fg1;
                }
            ]
        }
    }

    states [
        hovered when touch.has-hover && !alive: {
            background: T.bg2;
        }
        alive when alive: {
            background: T.fg1.darker(0.1);
        }
        none when !touch.has-hover && !alive: {
            background: transparent;
        }
    ]
}

export component ComboBox inherits Rectangle {
    in property <[string]> data;

    in property <color> font-color: T.fg1;
    in property <length> font-size: T.font5;
    in-out property <int> active-index: 0;
    in-out property <string> active: data.length > 0 ? data[active-index] : "";
    in property <length> popup-height: 300px;

    background: T.bg4;
    border-radius: T.bor-radius;

    touch := TouchArea {
        clicked => {
            options.show();
        }
    }

    layout := HorizontalLayout {
        padding-left: T.gap;
        padding-right: self.padding-left;
        padding-top: T.gap / 2;
        padding-bottom: self.padding-top;
        spacing: T.gap;

        alignment: space-between;

        Text {
            text: active-index < data.length ? data[active-index] : "";
            color: font-color;
            font-size: root.font-size;
            vertical-alignment: center;
            height: 100%;
        }

        VerticalLayout {
            alignment: center;
            Image {
                source: @image-url("../Assets/Icons/Down.png");
                height: self.width;
                width: root.font-size;
                colorize: font-color;
            }
        }
    }

    options := PopupWindow {
        width: max(self.preferred-width, layout.width);
        height: min(root.popup-height, self.preferred-height);

        close-policy: close-on-click;

        Rectangle {
            background: T.bg4;
            border-radius: T.bor-radius;
            border-width: 1px;
            border-color: #a2a2a2;

            Flickable {
                VerticalLayout {
                    padding: T.gap / 2;
                    spacing: T.gap / 2;
                    alignment: start;

                    for name[index] in data: ComboBox-Button {
                        title: name;
                        id: index;
                        font-size: T.font5;

                        clicked(id) => {
                            active-index = id;
                        }
                    }
                }
            }
        }
    }
}
