import { Theme as T } from "../Theme.slint";

export struct HeaderSize { label-size: length, desc-size: length }


export component Header inherits Rectangle {

    in property <{ label: string, desc: string }> header: { label: "Page", desc:"This is Page description" };
    in property <HeaderSize> header-font-size: { label-size: T.font2, desc-size: T.font5 };
    in property <{ label-color: color, desc-color: color }> header-color: { label-color: T.fg1, desc-color: T.fg3 };

    height: self.preferred-height;
    VerticalLayout {
        alignment: start;

        Text {
            text: root.header.label;
            font-size: root.header-font-size.label-size;
            horizontal-alignment: left;
            vertical-alignment: center;
            color: root.header-color.label-color;
        }

        Text {
            text: root.header.desc;
            font-size: root.header-font-size.desc-size;
            horizontal-alignment: left;
            vertical-alignment: center;
            color: root.header-color.desc-color;
        }
    }
}
