import { Theme as T } from "../Theme.slint";

export component InputText inherits Rectangle {
    in property <string> placeholder: "Enter here...";
    in-out property <string> input: "";
    in property <length> font-size: T.font4;

    height: root.font-size * 2;
    background: T.bg4;
    border-radius: T.bor-radius;

    forward-focus: input-field;
    HorizontalLayout {
        padding-left: T.gap;
        padding-right: self.padding-left;
        padding-top: T.gap / 2;
        padding-bottom: self.padding-top;

        touch := TouchArea {
            clicked => {
                input-field.focus();
            }

            VerticalLayout {
                if !input-field.has-focus && input.is-empty: Text {
                    height: 100%;
                    width: 100%;
                    text: placeholder;
                    color: T.fg3;
                    font-size: T.font5;
                    vertical-alignment: center;
                    horizontal-alignment: left;
                }

                // background: root.background;

               
                    FocusScope {
                    visible: input-field.has-focus || !input.is-empty;
                    input-field := TextInput {
                        text: input;
                        color: T.fg1;
                        font-size: root.font-size;
                        width: max(parent.width, self.preferred-width);
                        vertical-alignment: center;

                        private property <length> margin: 1rem;
                        cursor-position-changed(cursor-position) => {
                            if cursor-position.x + self.x < margin {
                                self.x = - cursor-position.x + margin;
                            } else if cursor-position.x + self.x > parent.width - margin - self.text-cursor-width {
                                self.x = parent.width - cursor-position.x - margin - self.text-cursor-width;
                            }
                        }

                        edited => {
                            root.input = input-field.text;
                            debug(input);
                        }

                        accepted => {
                            input = input-field.text;
                            if input.is-empty {
                                input-field.clear-focus();
                            }
                        }
                    }
                }
            }
        }
    }
}


export component Input-Item inherits Rectangle {
    in property <string> title: "Title";
    in property <string> placeholder: "Placeholder";
    in property <color> title-color: T.fg2;

    height: self.preferred-height;

    VerticalLayout {
        spacing: T.gap / 2;

        Text {
            text: root.title;
            font-size: T.font4;
            color: root.title-color;
        }

        InputText {
            placeholder: root.placeholder;
            height: T.font4 * 2;
        }
    }
}
