import { Theme as T } from "../Theme.slint";
import { HL } from "Base.slint";

export component LR-List-Item inherits Rectangle {

    in property <string> left-title;
    in property <string> right-title;

    in property <color> right-color: T.fg2;

    background: T.bg3;
    border-radius: T.bor-radius;

    HorizontalLayout {
        padding-top: T.gap / 2;
        padding-bottom: self.padding-top;
        padding-left: T.gap;
        padding-right: self.padding-left;

        spacing: T.gap * 2;

        VerticalLayout {
            spacing: T.gap / 2;
            Text {
                text: root.left-title;
                font-size: T.font4;
                color: T.fg2;
            }

            @children
        }

        Text {
            text: "₹ " + root.right-title;
            font-size: T.font4;
            horizontal-alignment: right;
            font-weight: 800;
            color: root.right-color;
        }
    }
}

export component LR-Text-Item inherits Rectangle {
    in property <{ lval: string, rval: string }> values: { lval: "Left", rval: "Right" };
    in property <color> font-color: T.fg2;
    in property <length> font-size;

    height: self.preferred-height;
    border-radius: T.bor-radius;
    

    HorizontalLayout {
        padding: T.gap / 2;
        padding-left: T.gap;
        padding-right: self.padding-left;

        alignment: space-between;

        for item in [values.lval, values.rval]: Text {
            text: item;
            color: values.rval.is-float() ? (values.rval.to-float() < 0 ? #ff4141: #69ff48) : T.fg1;
            font-size: root.font-size;
            vertical-alignment: center;
        }
    }

    background: values.rval.is-float() ? (values.rval.to-float() < 0 ? #ff41413a: #69ff483d) : T.bg3;
}
