import { Theme as T } from "../../Theme.slint";
import { Header, HBarChart, Page } from "../../Components/Components.slint";
import { Home-Today } from "Today.slint";
import { Banner } from "Banner.slint";
import {
    SVL,
    Card,
    Stat-Card,
    HL,
    Base2,
    VL,
} from "../../Components/Base.slint";

import {Glue} from "../../Glue.slint";
 

export component Home inherits Page {


    private property <float> total-amount: Glue.get_TotalAmount();
    private property <float> frozen-amount: Glue.get_FrozenAmount();

    page-header: {
        label: "Dashboard",
        desc: "Get a quick glance of all of your expenditures and savings"
    };

    VL {
        spacing: T.gap * 2;
        HL {
            vertical-stretch: 0.4;
            Banner { }

            VL {
                alignment: end;
                Stat-Card {
                    background: T.bg3;
                    stat: { label: total-amount - frozen-amount, desc: "Safe Balance" };
                }

                HL {
                    width: self.preferred-width;
                    Stat-Card {
                        background: T.bg3;
                        stat: { label: total-amount, desc: "Total Balance" };
                    }

                    Stat-Card {
                        background: T.bg3;
                        stat: { label: frozen-amount, desc: "Locked Balance" };
                    }
                }
            }
        }

        HL {
            spacing: T.gap * 2;

            Home-Today {
                min-width: 300px;
                max-width: 400px;
                data: Glue.get_TodaysRecords();
            }

            Card {
                card-header: { label: "₹ 37,090", desc: "Track your current balance here" };

                HBarChart { }
            }
        }
    }
}
