import { Theme as T } from "../../Theme.slint";
import {
    Header,
    Card,
    Base3,
    VL,
    Stat-Card,
    HL,
    Button,
    Base2,
} from "../../Components/Components.slint";
import { Goal-Detail } from "../../DataTypes.slint";
import { SVL } from "../../Components/Base.slint";


export component Goal-Card inherits Base2 {
    in property <Goal-Detail> data;
    private property <float> percent: root.data.saved / root.data.total * 100;

    callback clicked();

    border-width: 2px;
    border-color: tc.has-hover ? #0080ffbe : transparent;

    tc := TouchArea {
        clicked => { root.clicked() }
    }

    SVL {
        HL {
            alignment: space-between;
            Header {
                header: { label: data.name, desc: data.date + "   " + data.time };
                header-color: { label-color: T.fg1, desc-color: T.fg3 };
                header-font-size: { label-size: T.font3, desc-size: T.font5 };
            }
        }

        contents := VerticalLayout {
            spacing: T.gap;

            HL {
                alignment: start;

                for item in [
                    { title: "Total Amount", amount: root.data.total },
                    { title: "Saved Amount", amount:root.data.saved }
                ]: Stat-Card {
                    background: T.bg3;
                    stat: { label: item.amount, desc: item.title };
                    stat-font-size: { label-size: T.font4, desc-size: T.font5 };
                }
            }

            Base3 {
                height: self.preferred-height;
                VL {
                    padding: T.gap;
                    HL {
                        Text {
                            text: "Progress";
                            font-size: T.font4;
                            color: T.fg2;
                            horizontal-alignment: left;
                            vertical-alignment: center;
                        }

                        Text {
                            text: percent.to-fixed(2) + " %";
                            font-size: T.font4;
                            horizontal-alignment: right;
                            vertical-alignment: center;

                            color: {
                                if percent < 20.00 { #ff3636; }
                                else if percent < 40.00 { #ff9114; }
                                else if percent < 80.00 { #51aeff; }
                                else {
                                    #00ff3c;
                                }
                            }
                        }
                    }

                    fill-chart := Rectangle {
                        height: 20px;
                        border-radius: T.bor-radius;
                        background: T.bg1;

                        Rectangle {
                            border-radius: T.bor-radius;
                            border-width: 1px;

                            background: {
                                if percent < 20.00 { #ff0000ce; }
                                else if percent < 40.00 { #ff8400b6; }
                                else if percent < 80.00 { #0088ffbb; }
                                else {
                                    #00ff3ca4;
                                }
                            }

                            height: 10px;
                            x: 5px;
                            y: 5px;
                            width: (parent.width - 10px) * root.percent / 100;
                        }
                    }
                }
            }
        }
    }
}



export component Goal-Add-Card inherits Rectangle {
    border-width: tc.has-hover ? 2px : 1px;
    border-color: tc.has-hover ? #0055ffbd : #00ff3395;
    background: tc.has-hover ? T.bg1 : T.bg2;
    border-radius: T.bor-radius;

    callback clicked();

    SVL {
        alignment: center;

        Text {
            text: "+";
            font-size: T.font1 * 2;
            horizontal-alignment: center;
        }

        Text {
            text: "Add new Goal";
            horizontal-alignment: center;
            font-size: T.font4;
            color: T.fg3;
        }
    }

    tc := TouchArea {
        clicked => { root.clicked(); }
    }
}
