
import { Theme as T } from "../../Theme.slint";
import {
    Header,
    VL,
    HL,
    Base2,
    Base3,
    Card,
} from "../../Components/Components.slint";
import { Goal-Card, Goal-Add-Card } from "GoalCard.slint";
import { New-Goal-Form } from "NewGoal.slint";
import { Page, SVL } from "../../Components/Base.slint";
import { Goal-Detail } from "../../DataTypes.slint";
import { Goal-Summary } from "Summary.slint";
import { Glue } from "../../Glue.slint";


export component Goals inherits Page {
    private property <float> total-amount: Glue.get_TotalAmount();
    private property <float> frozen-amount: Glue.get_FrozenAmount();
    private property <[Goal-Detail]> goals: Glue.get_Goals();

    min-width: 800px;
    max-width: 1200px;
    page-header: { label: "Goals", desc: "Manage your Goals about expenditures, savings here" };

    HL {

        detail := Goal-Summary {
            min-width: 360px;
            data: { total: root.total-amount, frozen:root.frozen-amount, goals: root.goals };
        }

        Flickable {
            HL {
                alignment: space-around;
                VL {

                    spacing: T.gap * 2;
                    alignment: goals.length > 0 ? start : center;

                    Goal-Add-Card {
                        clicked => { add.show(); }
                        add := PopupWindow {
                            width: self.preferred-width;

                            close-policy: no-auto-close;

                            New-Goal-Form {
                                border-width: 1px;
                                border-color: T.fg3;

                                create-clicked => {
                                    parent.close()
                                }

                                discard-clicked => {
                                    parent.close();
                                }
                            }
                        }
                    }

                    for item[index] in goals: Goal-Card {
                        data: item;
                        min-width: 600px;
                        clicked => {
                        }
                    }
                }
            }
        }

        // Goal-Detail {
        //     min-width: 400px;
        // }
    }
}
