import { Theme as T } from "../../Theme.slint";
import { Header } from "../../Components/Components.slint";


export component Goal-Card inherits Rectangle {
    in property <string> title: "My Goal";
    in property <int> amount: 45000;
    in property <int> saved: 22200;

    height: self.preferred-height;

    private property <float> percent: root.saved / root.amount * 100;

    background: T.bg2;
    border-radius: T.bor-radius;
    border-width: tc.has-hover ? 2px: 1px;
    border-color: {
        if tc.has-hover { #0073ff }
        else if percent < 20.00 { #ff0000; }
        else if percent < 40.00 { #ff6f00; }
        else if percent < 80.00 { #ffb300a4; }
        else {
            #00ff3c;
        }
    }

    tc := TouchArea { }

    VerticalLayout {
        padding: T.gap * 2;
        spacing: 100px;

        Header {
            header: title;
            description: "24th march 2026";
            header-size: T.font3;
        }

        contents := VerticalLayout {
            // padding: T.gap;
            spacing: T.gap;
            height: self.preferred-height;

            HorizontalLayout {
                spacing: T.gap;
                alignment: start;

                for item in [
                    { title: "Total Amount", amount: root.amount },
                    { title: "Saved Amount", amount:root.saved }
                ]: Rectangle {
                    background: T.bg3;
                    border-radius: T.bor-radius;

                    VerticalLayout {
                        spacing: T.gap / 2;
                        padding-left: T.gap;
                        padding-right: self.padding-left;
                        padding-top: T.gap / 2;
                        padding-bottom: self.padding-top;
                        alignment: space-between;
                        height: self.preferred-height;

                        Text {

                            text: "₹ " + item.amount;
                            font-size: T.font4;
                            color: T.fg2;
                            horizontal-alignment: left;
                            vertical-alignment: center;
                        }

                        Text {
                            text: item.title;
                            font-size: T.font4;
                            color: T.fg3;
                            horizontal-alignment: left;
                            vertical-alignment: center;
                        }
                    }
                }
            }

            Rectangle {
                background: T.bg3;
                border-radius: T.bor-radius;
                height: self.preferred-height;

                VerticalLayout {
                    padding: T.gap;
                    spacing: T.gap;

                    HorizontalLayout {
                        Text {
                            text: "Progress";
                            font-size: T.font4;
                            color: T.fg2;
                            horizontal-alignment: left;
                            vertical-alignment: center;
                        }

                        Text {

                            text: percent.to-fixed(2) + " %";
                            font-size: T.font4;
                            horizontal-alignment: right;
                            vertical-alignment: center;

                            color: {
                                if percent < 20.00 { #ff0000; }
                                else if percent < 40.00 { #ff6f00; }
                                else if percent < 80.00 { #ffb300; }
                                else {
                                    #00ff3c;
                                }
                            }
                        }
                    }

                    bar-chart := Rectangle {
                        height: 20px;
                        border-radius: T.bor-radius;
                        background: T.bg4;

                        Rectangle {
                            border-radius: T.bor-radius;
                            border-width: 1px;
                            border-color: {
                                if percent < 20.00 { #ff0000; }
                                else if percent < 40.00 { #ff6f00; }
                                else if percent < 80.00 { #ffb300; }
                                else {
                                    #00ff3c;
                                }
                            }

                            background: {
                                if percent < 20.00 { #ff00002a; }
                                else if percent < 40.00 { #ff6f0021; }
                                else if percent < 80.00 { #ffb30033; }
                                else {
                                    #00ff3c2a;
                                }
                            }

                            height: 10px;
                            x: 5px;
                            y: 5px;
                            width: (parent.width - 10px) * saved / amount;
                        }
                    }
                }
            }
        }
    }
}


export component Goal-Add-Card inherits Rectangle {
    border-width: tc.has-hover ? 2px: 1px;
    border-color: tc.has-hover ? #0055ffbd : #00ff3395;
    background: tc.has-hover ? T.bg1 : T.bg2;
    border-radius: T.bor-radius;

    VerticalLayout {
        alignment: center;
        padding: T.gap;

        Text {
            text: "+";
            font-size: T.font1 * 2;
            horizontal-alignment: center;
        }

        Text {
            text: "Add new Goal";
            horizontal-alignment: center;
            font-size: T.font4;
            color: T.fg3;
        }
    }

    tc := TouchArea { }
}
