import { Theme as T } from "../../Theme.slint";
import {
    Header,
    Button,
    InputText,
    Input-Item,
    Card,
    HL,
    VL,
}  from "../../Components/Components.slint";



export component New-Goal-Form inherits Card {

    card-header: { label: "Add Goal", desc: "Create a new financial goal" };

    callback create-clicked();
    callback discard-clicked();

    background: T.bg2;
    border-radius: T.bor-radius;

    Input-Item {
        title: "Goal name";
        placeholder: "My Goal";
    }

    VL {
        HL {
            Input-Item {
                title: "Total Amount";
                placeholder: "₹ 10,000";
            }

            Input-Item {
                title: "Saved Amount";
                placeholder: "₹ 24,000";
            }
        }

        Text {
            text: "Available Balance: " + "₹ 14,783";
            font-size: T.font4;
        }

        Rectangle { }
    }

    HL {
        Button {
            title: "Create";
            bg-color: #3cb4ff;

            clicked => { create-clicked(); }
        }

        Button {
            title: "Discard";
            bg-color: #fe0000;

            clicked => { discard-clicked(); }
        }
    }
}
