import { Theme as T } from "../../Theme.slint";
import {
    Card,
    Header,
    Base3,
    Base2,
    SVL,
    VL,
} from "../../Components/Components.slint";
import { LR-Text-Item } from "../../Components/Item.slint";
import { LR-Text-Table } from "../../Components/Table.slint";
import { HL, Base1 } from "../../Components/Base.slint";

export component Goal-Detail inherits Card {
    card-header: { label: "Goal Name", desc: "Description of goal" };

    max-width: 450px;
    // min-width: 360px;

    
    VL {
        

        VerticalLayout {
            Base3 {
                min-width: 300px;
                SVL {
                    Header {
                        header: { label: "History", desc: "View your goal activity" };
                        header-font-size: { label-size: T.font4, desc-size: T.font5 };
                    }

                    Base1 {
                        VL {
                            padding: T.gap / 2;
                            LR-Text-Table {
                                col-title: { lval: "Category", rval: "Expense" };

                                //Mock data
                        
                            }
                        }
                    }
                }
            }
        }
    }
}
