export global Theme {
    out property <color> bg1: #000000;
    out property <color> bg2: #0c0c0c;
    out property <color> bg3: #1a1a1a;
    out property <color> bg4: #242424;
    out property <color> bg5: #5e5e5e;

    out property <color> fg1: #ffffff;
    out property <color> fg2: #c9c9c9;
    out property <color> fg3: #7b7b7b;
    out property <color> fg4: #424242;

    out property <length> font1: 48px;
    out property <length> font2: 36px;
    out property <length> font3: 24px;
    out property <length> font4: 18px;
    out property <length> font5: 16px;

    out property <length> gap: 10px;

    out property <length> bor-radius: 10px;
    out property <color> bor-color: #3e3e3e;

    out property <color> accent: red;
}
