
import { Theme as T } from "../../Theme.slint";
import {
    Page,
    Base2,
    VL,
    HL,
} from "../../Components/Components.slint";
import { Records-List } from "RecordItem.slint";
import { SVL, SHL } from "../../Components/Base.slint";
import { InputText } from "../../Components/Input.slint";
import { Record-Detail } from "../../DataTypes.slint";
import { Glue } from "../../Glue.slint";



export component Records inherits Page {

    private property <[Record-Detail]> data: Glue.get_Records();

    page-header: { label: "Records", desc: "Add, modify, lookup and delete your records here." };
    min-width: 800px;

    VL {
        spacing: T.gap * 1.5;
        toolbar := Base2 {
            border-width: 1px;
            border-color: #343434;

            SHL {
                alignment: end;
                spacing: T.gap;

                HL {

                    Text {
                        text: "70 records";
                        font-size: T.font4;
                        color: T.fg3;
                        horizontal-alignment: right;
                        vertical-alignment: center;
                    }

                    InputText {
                        placeholder: "Search";
                        width: 150px;
                    }
                }
            }
        }

        Records-List { }
    }
}
