import { Theme as T } from "../../Theme.slint";
import { Base3, HL } from "../../Components/Components.slint";
import { Base4, Base2, VL, SVL, Base1 } from "../../Components/Base.slint";
import { Record-Detail } from "../../DataTypes.slint";

export component RecordsItem inherits Base3 {

    in property <Record-Detail> data;

    HL {
        padding-top: T.gap;
        padding-bottom: self.padding-top;
        padding-left: T.gap * 2;
        padding-right: self.padding-left;
        spacing: T.gap * 2;
        alignment: space-between;

        VerticalLayout {
            spacing: T.gap / 2;

            Text {
                text: data.name;
                font-size: T.font3;
                color: T.fg2;
                horizontal-alignment: left;
                vertical-alignment: center;
            }

            HorizontalLayout {
                spacing: T.gap * 2;

                Text {
                    text: data.date;
                    font-size: T.font5;
                    color: T.fg3;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                }

                Text {
                    text: data.time;
                    font-size: T.font5;
                    color: T.fg3;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                }

                Text {
                    text: data.category;
                    font-size: T.font5;
                    color: T.fg3;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                }
            }
        }

        Text {
            text: data.amount > 0 ? data.amount: abs(data.amount);
            font-size: T.font3;
            color: data.amount < 0 ? #ff4d4d: #5cff66;
            font-weight: 800;
            horizontal-alignment: right;
            vertical-alignment: center;
        }
    }

    tc := TouchArea { }

    border-width: 1px;
    // background: data.amount < 0 ? #ff000016: #00ff111f;
    border-color: tc.has-hover ? #41b9ff : transparent;
}



export component Records-List inherits Rectangle {

    in property <[Record-Detail]> data;

    Flickable {
        HL {
            alignment: space-around;

            VerticalLayout {
                padding: T.gap;
                spacing: T.gap * 2;

                alignment: start;
                for item in data: RecordsItem {
                    data: item;
                    min-width: 700px;
                }
            }
        }
    }
}
