import { Theme as T } from "../../Theme.slint";
import { Base3, HL } from "../../Components/Components.slint";
import { Base4, Base2, VL, SVL, Base1 } from "../../Components/Base.slint";

export component RecordsItem inherits Base3 {

    in property <[string]> data:["Momos", "12th Mar 2026", "12:08 AM", "Fast Food", "Deduct", "500"];

    HL {
        padding-top: T.gap / 2;
        padding-bottom: self.padding-top;
        padding-left: T.gap;
        padding-right: self.padding-left;
        spacing: T.gap * 2;
        alignment: space-between;

        VerticalLayout {
            spacing: T.gap / 2;

            Text {
                text: data[0];
                font-size: T.font3;
                color: T.fg1;
                horizontal-alignment: left;
                vertical-alignment: center;
            }

            HorizontalLayout {
                spacing: T.gap * 2;

                Text {
                    text: data[1];
                    font-size: T.font5;
                    color: T.fg2;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                }

                Text {
                    text: data[2];
                    font-size: T.font5;
                    color: T.fg2;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                }

                Text {
                    text: data[3];
                    font-size: T.font5;
                    color: T.fg2;
                    horizontal-alignment: left;
                    vertical-alignment: center;
                }
            }
        }

        Text {
            text: data[5];
            font-size: T.font3;
            font-weight: 800;
            horizontal-alignment: right;
            vertical-alignment: center;
        }
    }

    tc := TouchArea { }

    border-width: 1px;
    border-color: tc.has-hover ? #41b9ff : transparent;
}



export component Records-List inherits Rectangle {

    in property <[[string]]> data: [
        ["Momos", "12th Mar 2026", "12:08 AM", "Fast Food", "Deduct", "500"],
        ["Coca Cola", "21st Jun 2026", "06:08 PM", "Drinks", "Deduct", "1900"]
    ];

    Flickable {
        HL {
            alignment: space-around;

            VerticalLayout {
                padding: T.gap;
                spacing: T.gap;

                alignment: start;
                for item in data: RecordsItem {
                    data: item;
                    min-width: 600px;
                }
            }
        }
    }
}
