
import { Theme as T } from "../../Theme.slint";
import {
    Page,
    Base2,
    VL,
    HL,
} from "../../Components/Components.slint";
import { Records-List } from "RecordItem.slint";
import { SVL, SHL } from "../../Components/Base.slint";
import { InputText } from "../../Components/Input.slint";
import { Record-Detail } from "../../DataTypes.slint";
import { Glue } from "../../Glue.slint";
import { Button } from "../../Components/Button.slint";
import { Record-Form } from "../../Components/Record-Form.slint";



export component Records inherits Page {

    function load() {
        data = Glue.get_Records();
    }

    private property <[Record-Detail]> data: Glue.get_Records();

    page-header: { label: "Records", desc: "Add, modify, lookup and delete your records here." };
    min-width: 800px;

    VL {
        spacing: T.gap * 1.5;
        toolbar := Base2 {
            border-width: 1px;
            border-color: #343434;

            SHL {
                alignment: space-between;
                spacing: T.gap;

                Button {
                    title: "New record";
                    bg-color: T.fg2;

                    clicked => {
                        add.show();
                    }

                    add := PopupWindow {
                        x: parent.width;
                        y: parent.height;

                        close-policy: no-auto-close;
                        Record-Form {
                            cancel-clicked => {
                                parent.close();
                            }

                            save-clicked => {
                                parent.close();
                                load();
                            }
                        }
                    }
                }

                HL {
                    Text {
                        text: root.data.length + " records";
                        font-size: T.font4;
                        color: T.fg3;
                        horizontal-alignment: right;
                        vertical-alignment: center;
                    }

                    InputText {
                        placeholder: "Search";
                        width: 150px;
                    }
                }
            }
        }

        Records-List {
            data: root.data;
        }
    }
}
