import { Theme as T } from "../../Theme.slint";
import { Header, LR-Gapped-Item } from "../../Components/Components.slint";
import { Button } from "../../Components/Button.slint";

export struct ExpenseItem {
    name: string,
    amount: int,
}

export struct DayExpenses {
    items: [ExpenseItem],
}

export component Detail-Daily-Expense inherits Rectangle {

    in property <DayExpenses> data;

    background: T.bg2;
    border-radius: T.bor-radius;
    border-width: 1px;
    border-color: T.fg3;

    VerticalLayout {
        padding: T.gap * 2;
        spacing: T.gap;

        HorizontalLayout {
            alignment: space-between;
            spacing: T.gap * 2;

            Header {
                header: "Daily Expenses";
                description: "Daily account here";
                header-size: T.font3;
            }

            Button {
                title: "Add";
                height: self.preferred-height;
                font-size: T.font5;
                bg-color: T.fg2;
            }
        }

        HorizontalLayout {
            padding: T.gap;
            spacing: T.gap;

            Rectangle {
                background: T.bg3;
                border-radius: T.bor-radius;

                VerticalLayout {
                    padding: T.gap / 2;
                    spacing: T.gap / 2;

                    HorizontalLayout {
                        padding-left: T.gap;
                        padding-right: self.padding-left;
                        spacing: T.gap;
                        Text {
                            text: "Title";
                            font-size: T.font4;
                        }

                        Text {
                            text: "Amount";
                            font-size: T.font4;
                            horizontal-alignment: right;
                        }
                    }

                    Rectangle {
                        background: T.bg2;
                        border-radius: T.bor-radius;

                        Flickable {
                            VerticalLayout {
                                alignment: start;
                                padding: T.gap;
                                spacing: T.gap;

                                for item in data.items: LR-Gapped-Item {
                                    left-title: item.name;
                                    right-title: item.amount > 0 ? item.amount : abs(item.amount);
                                    background: T.bg3;
                                    right-color: item.amount > 0 ? #10bb00 : #c80000;

                                    HorizontalLayout {
                                        spacing: T.gap;
                                        Text {
                                            text: "Commute";
                                            font-size: T.font5;
                                            color: T.fg3;
                                        }

                                        Text {
                                            text: "12:60PM";
                                            font-size: T.font5;
                                            color: T.fg3;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

            VerticalLayout {
                alignment: start;
                spacing: T.gap;

                width: self.preferred-width;
                private property <[{ amount: int, title: string }]> total: [{ amount: 3180, title: "Total Spent" }, { amount: 720, title: "Total Received" }];

                for item in total: Rectangle {
                    background: T.bg3;
                    border-radius: T.bor-radius;

                    VerticalLayout {
                        padding: T.gap;
                        height: self.preferred-height;

                        Rectangle {
                            Text {
                                height: 100%;
                                width: 100%;
                                text: item.amount;
                                font-size: T.font4;
                                horizontal-alignment: left;
                                color: T.fg1;
                            }
                        }

                        Rectangle {
                            Text {
                                height: 100%;
                                width: 100%;
                                text: item.title;
                                font-size: T.font5;
                                horizontal-alignment: left;
                                color: T.fg3;
                            }
                        }
                    }
                }
            }
        }
    }
}
