import { Theme as T } from "../../Theme.slint";
import { Button, ComboBox } from "../../Components/Components.slint";

export component Track-Toolbar inherits Rectangle {
    background: T.bg3;
    border-radius: T.gap;

    HorizontalLayout {
        Rectangle {
            height: self.preferred-height;

            HorizontalLayout {
                spacing: T.gap / 2;
                padding: T.gap / 2;
                alignment: space-between;

                // Toolbar left panel
                    HorizontalLayout {
                    spacing: T.gap;

                    Rectangle {
                        background: T.bg2;
                        border-radius: T.bor-radius;
                        HorizontalLayout {
                            spacing: 1px;
                            Rectangle {
                            // background: #00ff0d2e;
                            border-top-left-radius: T.bor-radius;
                                border-bottom-left-radius: T.bor-radius;

                                HorizontalLayout {
                                    padding-left: T.gap;
                                    padding-right: self.padding-left;

                                    Text {
                                        text: "+ ₹7200";
                                        vertical-alignment: center;
                                        horizontal-alignment: center;
                                        font-size: T.font4;
                                        color: #00ff0d;
                                        font-weight: 800;
                                    }
                                }
                            }

                            Rectangle {
                                width: 1px;
                                background: T.bg3;
                            }

                            Rectangle {
                            // background: #ff00002d;
                            border-top-right-radius: T.bor-radius;
                                border-bottom-right-radius: T.bor-radius;

                                HorizontalLayout {
                                    padding-left: T.gap;
                                    padding-right: self.padding-left;

                                    Text {
                                        text: "+ 2800";
                                        vertical-alignment: center;
                                        horizontal-alignment: center;
                                        font-size: T.font4;
                                        color: #ff2020;
                                        font-weight: 800;
                                    }
                                }
                            }
                        }
                    }

                    // total := Rectangle {
                    //     background: T.bg2;
                    //     border-radius: T.bor-radius;
                    //     border-width: 1px;

                    //     HorizontalLayout {
                    //         spacing: T.gap;
                    //         padding-left: T.gap;
                    //         padding-right: self.padding-left;

                    //         Text {
                    //             text: "- ₹13000";
                    //             vertical-alignment: center;
                    //             horizontal-alignment: center;
                    //             font-size: T.font4;
                    //             color: #ffffffd4;
                    //             font-weight: 800;
                    //         }
                    //     }
                    // }
                }

                @children

                toolbar-right-panel := HorizontalLayout {
                    spacing: T.gap;

                    ComboBox {
                        width: 120px;

                        data: [
                            "January",
                            "February",
                            "March",
                            "April",
                            "May",
                            "June",
                            "July",
                            "August",
                            "September",
                            "October",
                            "Novemeber",
                            "December"
                        ];
                    }

                    ComboBox {
                        data: ["2026", "2025", "2024", "2023"];
                    }
                }
            }
        }
    }
}
