import { Theme as T } from "../../Theme.slint";
import {
    Sidebar,
    Button,
    HBarChart,
    Page,
    Base2,
    VL,
    Card,
    HL,
    Base3,
    LR-List-Item,
    Base4,
    Base5,
    LR-Text-Table,
} from "../../Components/Components.slint";
import { Track-Toolbar } from "Toolbar.slint";
import { SVL, Base1 } from "../../Components/Base.slint";
import {
    LR-Text-Item,
} from "../../Components/Item.slint";


import { Track-SidePane } from "Sidebar.slint";
import { Glue } from "../../Glue.slint";




export component Track inherits Page {
    private property <{ year: int, month: int, date: int }> present: Glue.get_CurrentDateBreakdown();

    private property <{ year: int, month: int, date: int }> selected: Glue.get_CurrentDateBreakdown();
    page-header: { label: "Track", desc: "Track your savings and expenditures over time here" };

    HL {
        spacing: T.gap * 2;
        VL {
            spacing: T.gap * 2;
            Card {
                card-header: {
                    label: "Monthly Expenditure Chart",
                    desc: "Track your expenditure throughout last 30 days in a glance"
                };

                HBarChart {
                    max-height: 200px;
                }
            }

            HL {
                alignment: start;
                Card {
                    min-width: 360px;
                    card-header: { label: "This Month", desc: "Categorical activities within this month" };

                    Base1 {
                        VL {
                            padding: T.gap;
                            cat := LR-Text-Table {
                                col-title: { lval: "Category", rval: "Expense" };

                                data: Glue.get_MonthlyCategoryTotals(selected.year, selected.month);
                            }
                        }
                    }
                }
            }
        }

        Track-SidePane {
            min-width: 320px;
            max-width: 380px;

            selected-date: present.date;
            month-in: present.month - 1;
            year-in: present.year - 2026;

            selections(day, month, year) => {
                selected.month = month;
                selected.year = year;
            }

            monthChanged => {
                // cat.data = Glue.get_MonthlyCategoryTotals(present.year.to-float(), present.month.to-float());
            }
        }
    }
}
